exec sh -c 'eval "$(ssh-agent -s)" && ssh-add ~/.ssh/id_ed25519'
exec_always sh -c 'pkill waybar; waybar'
exec dunst
exec systemctl --user start mpd-mpris
exec wl-paste --type text --watch cliphist store
exec wl-paste --type image --watch cliphist store
exec wlsunset -s 19:00 -S 07:00 -t 3000 -T 5500
exec ~/.config/sway/scripts/song-notify.sh
