input type:keyboard {
    xkb_layout "latam,us"
    xkb_options caps:escape
    xkb_numlock enabled
}

input type:tablet_tool {
    map_to_output HDMI-A-1
    calibration_matrix -1 0 1 0 1 0
    # left_handed enable
}

# input type:touchpad { 
#     dwt enabled 
#     tap enabled 
#     natural_scroll enabled
#     middle_emulation enabled
# }
