set $term kitty
set $menu rofi -show drun
set $filemanager kitty -e yazi

# Media playback
    bindsym XF86AudioPrev exec playerctl previous
    bindsym XF86AudioPlay exec playerctl play-pause
    bindsym XF86AudioNext exec playerctl next

# Volume
    bindsym XF86AudioMute exec wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
    bindsym XF86AudioLowerVolume exec wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
    bindsym XF86AudioRaiseVolume exec wpctl set-volume -l 1.0 @DEFAULT_AUDIO_SINK@ 5%+

# screenshots
bindsym Mod4+Shift+s exec sh -c 'grim -g "$(slurp)" - | tee ~/Pictures/screenshots/screenshot-$(date +%Y-%m-%d_%H-%M-%S).png | wl-copy'
bindsym Ctrl+Mod4+Shift+s exec sh -c 'grim ~/Pictures/screenshots/screenshot-$(date +%Y-%m-%d_%H-%M-%S).png'

# clipboard (borrar con cliphist wipe)
bindsym $mod+Shift+v exec sh -c 'cliphist list | rofi -dmenu | cliphist decode | wl-copy'

# app launchers
    bindsym $mod+Return exec $term
    bindsym $mod+Shift+Return exec kitty -e yazi
    bindsym $mod+BackSpace exec zen-browser
    bindsym $mod+Shift+BackSpace exec zen-browser --private-window
    bindsym --locked XF86MonBrightnessDown exec kitty -e yazi
    bindsym --locked Shift+XF86MonBrightnessDown exec $filemanager
    bindsym $mod+m exec kitty rmpc
    bindsym $mod+s exec localsend
    bindsym $mod+space exec $menu
    bindsym Mod4+space exec rofi -show window

bindsym insert exec ~/.config/sway/scripts/menu.sh
bindsym shift+insert exec ~/.config/sway/scripts/power.sh
