} add speed 0.5
{ add speed -0.5
] add speed 0.1
[ add speed -0.1

UP add volume 5
DOWN add volume -5

Ctrl+Left   playlist-prev
Ctrl+Right  playlist-next

SPACE           cycle pause                         #event: click
SPACE           no-osd set speed 3; set pause no    #event: press
SPACE           ignore                              #event: release

B script_message bookmarker-menu
b script_message bookmarker-quick-save
ctrl+b script_message bookmarker-quick-load

MBTN_LEFT           cycle pause                         #event: click
MBTN_LEFT           no-osd set speed 3; set pause no    #event: press
MBTN_LEFT           ignore                              #event: release

1 ab-loop

2 screenshot

a cycle audio

! cycle-values loop-file "inf" "no"
S cycle sub-visibility
s cycle sub

l seek 30
h seek -30

k add volume 5
j add volume -5

PGUP add chapter -1
PGDWN add chapter 1
