#font
sub-ass-override=force
sub-font="JetBrainsMono Nerd Font"
osd-font="JetBrainsMono Nerd Font"
sub-font-size=30
sub-color="#FFFF00"
sub-border-style=background-box
profile=sub-box
sub-back-color="#90000000"
sub-border-size=0
sub-auto=all
sub-file-paths=subs:subtitles:Subs:Subtitles:**
#auto sub/audio track
sid=1
aid=1

#misc
fs=yes #start on fullscreen
no-osd-bar
screenshot-directory=~/Pictures/mpv-screenshots/
gpu-context=x11egl

# chapters-file=chapters.txt
