require("plugins.highlight-colors")
require("plugins.cmp")
require("plugins.lsp")
require("plugins.treesitter")
require("plugins.alpha")
require("plugins.autopairs")
require("plugins.blankline")
require("plugins.bullet")
require("plugins.markdown")
require("plugins.neoscroll")
require("plugins.oil")
require("plugins.fzf-lua")
require("plugins.yazi")
require("plugins.surround")
require("plugins.gitsigns")
require("plugins.lualine")
require("plugins.treesitter-ctx")
require("plugins.calculate")
require("plugins.aerial")

-- theme
require("plugins.themes.gruvbox")
