# Options
set-option -g status-position top
set -sg terminal-overrides ",*:RGB"  # true color support
set -g escape-time 0  # disable delays on escape sequences
set -g mouse on
set -g renumber-windows on  # keep numbering sequential
set -g repeat-time 1000  # increase "prefix-free" window

# Options: start indexes from 1
set -g base-index 1
set -g pane-base-index 1

# Change prefix
unbind C-b
set -g prefix |
bind | send-prefix

# Theme: borders
set -g pane-border-lines simple
set -g pane-border-style fg=black,bright
set -g pane-active-border-style fg=yellow

# Theme: status
set -g status-style bg=default,fg=black,bright
set -g status-left ""
# set -g status-right "#[fg=white,bright]#W:#[fg=white,bright]#S"
set -g status-right "#[fg=white,bright]#S"

# Theme: status (windows)
# set -g window-status-format "●"
# set -g window-status-current-format "●"

set -g window-status-style "#{?window_zoomed_flag,fg=yellow,fg=white\#,nobold}"
set -g window-status-current-style "#{?window_zoomed_flag,fg=yellow,fg=pink\#,nobold}"
set -g window-status-bell-style "fg=red,nobold"

# Keybindings: wasd
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind -r H resize-pane -L
bind -r J resize-pane -D
bind -r K resize-pane -U
bind -r L resize-pane -R

# Keybindings: disable repeat for arrows
# bind Up select-pane -U
# bind Left select-pane -L
# bind Down select-pane -D
# bind Right select-pane -R

# Keybindings: split
# bind h split-window -h
# bind | split-window -h
# bind v split-window -v
# bind - split-window -v

# Keybindings: windows
bind -n C-Tab next-window
bind -n C-S-Tab previous-window

bind -n M-1 select-window -t :1
bind -n M-2 select-window -t :2
bind -n M-3 select-window -t :3
bind -n M-4 select-window -t :4
bind -n M-5 select-window -t :5
bind -n M-6 select-window -t :6
bind -n M-7 select-window -t :7
bind -n M-8 select-window -t :8
bind -n M-9 select-window -t :9

# Keybindings: other
bind f resize-pane -Z
bind d detach-client
bind r source-file ~/.config/tmux/tmux.conf
# bind e choose-window -Z

# Set correct terminal capabilities
set -g default-terminal "tmux-256color"
set -as terminal-overrides ",xterm-256color:RGB"
set -as terminal-overrides ',*:Smulx=\E[4\:%p1%dm'  # undercurl support
set -as terminal-overrides ',*:Setulc=\E[58\:2\:\:%p1%d\:%p2%d\:%p3%dm' # underscore colours

# Pass through environment variables needed for Wayland/Kitty
set -ga update-environment TERM
set -ga update-environment TERM_PROGRAM
set -ga update-environment WAYLAND_DISPLAY
set -ga update-environment XDG_CURRENT_DESKTOP
set -ga update-environment KITTY_WINDOW_ID
# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
