[General]
bookmarks=/home/tom
lastDisplay=0
maximizedWindow=true
printColor=false
printFitToPage=true
printLandscape=false
printPdfDefault=false
savedPaths=/home/tom, /home/tom/Desktop, /home/tom/Documents, /home/tom/dotfiles, /home/tom/Downloads, /home/tom/music, /home/tom/notes, /home/tom/Pictures, /home/tom/tlen
windowGeometry=@Rect(0 0 952 1026)
